/* Copyright 2025 Marc Scheffer
 *
 * helmBoy is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 *
 * This work is based on bepzi's Helm project, <https://github.com/bepzi/helm>,
 * itself based on Matt Tytel's Helm <https://tytel.org/helm/>
 *
 * helmBoy is distributedin the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with helmBoy.  If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once
#ifndef OSCILLOSCOPE_H
#define OSCILLOSCOPE_H

/**
 * @file oscilloscope.h
 * @brief Visualisation temps réel des formes d'onde audio.
 */

#include <JuceHeader.h>
#include "memory.h"

/**
 * @brief Real-time audio waveform visualization component
 * @ingroup user_interface
 *
 * Oscilloscope provides real-time visualization of audio signals, displaying
 * waveforms as they are generated by the synthesizer. This component offers
 * valuable visual feedback for sound design, allowing users to see the
 * immediate effects of parameter changes on the generated audio signal.
 *
 * @section scope_features Key Features
 *
 * - **Real-time Display**: Live audio waveform visualization
 * - **Memory Integration**: Direct connection to synthesis engine output
 * - **Smooth Rendering**: Anti-aliased waveform drawing
 * - **Background Caching**: Optimized rendering performance
 * - **Configurable Updates**: Adjustable refresh rate and feedback settings
 * - **Path Generation**: Efficient waveform path construction
 *
 * @section scope_display Display Characteristics
 *
 * The oscilloscope provides:
 * - **Time Domain View**: Traditional oscilloscope-style waveform display
 * - **Amplitude Scaling**: Automatic or manual amplitude scaling
 * - **Trigger Options**: Various triggering modes for stable display
 * - **Grid Overlay**: Optional reference grid for measurement
 * - **Color Coding**: Customizable waveform colors and styling
 *
 * @section scope_integration System Integration
 *
 * ```cpp
 * // Legacy raw-buffer hookup; keep the supplied storage alive while in use.
 * Oscilloscope* scope = new Oscilloscope();
 * scope->setOutputMemory(callerOwnedSnapshot);
 * scope->showRealtimeFeedback(true);
 *
 * // The oscilloscope automatically updates from the audio buffer
 * // Timer callback handles refresh rate and rendering
 * ```
 *
 * @section performance Performance Optimization
 *
 * The oscilloscope is optimized for real-time use:
 * - **Efficient Path Updates**: Only redraws when necessary
 * - **Background Caching**: Reduces redraw overhead
 * - **Timer-based Updates**: Controlled refresh rate
 * - **Memory Ownership**: Caller-owned waveform snapshot (legacy API)
 * - **SIMD-friendly Operations**: Vectorized path generation
 *
 * @section visual_customization Visual Customization
 *
 * Supports customization of:
 * - Waveform color and thickness
 * - Background styling and grid patterns
 * - Update rate and smoothing
 * - Amplitude scaling and offset
 * - Trigger sensitivity and mode
 *
 * @see Timer
 * @see Component
 * @see HelmBoyEngine
 * @see OpenGLOscilloscope
 */
class Oscilloscope : public Component, public Timer {
  public:
    Oscilloscope();
    ~Oscilloscope();

    void timerCallback() override;
    void paint(Graphics& g) override;
    void paintBackground(Graphics& g);
    void resized() override;

    void resetWavePath();
    [[deprecated("Unsafe raw buffer; provide an owned snapshot")]]
    void setOutputMemory(const float* memory) { output_memory_ = memory; }
    void showRealtimeFeedback(bool show_feedback = true);

  private:
    const float* output_memory_;
    Path wave_path_;
    Image background_;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(Oscilloscope)
};

#endif // OSCILLOSCOPE_H
